version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: parser
      MYSQL_USER: bestuser
      MYSQL_PASSWORD: secretPassword

#    volumes:
#      - mysql_data:/var/lib/mysql

    ports:
      - "3307:3306"

    restart: unless-stopped

    networks:
      - parser-net

networks:
  parser-net:
    driver: bridge

#volumes:
#  mysql_data:
