version: '3'

services:

  mysql-parse:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: parser
      MYSQL_USER: bestuser
      MYSQL_PASSWORD: secretPassword
    ports:
      - "3307:3306"
    restart: unless-stopped
    networks:
      - parser-net

  postgres-stock:
    image: postgres:latest
    environment:
      POSTGRES_DB: stock
      POSTGRES_USER: bestuser
      POSTGRES_PASSWORD: secretPassword
    ports:
      - "5431:5432"
    restart: unless-stopped
#    restart: no
    networks:
      - parser-net

  postgres-product:
    image: postgres:latest
    environment:
      POSTGRES_DB: product
      POSTGRES_USER: bestuser
      POSTGRES_PASSWORD: secretPassword
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - parser-net

  postgres-order:
    image: postgres:latest
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: bestuser
      POSTGRES_PASSWORD: secretPassword
    ports:
      - "5434:5432"
    restart: unless-stopped
    networks:
      - parser-net

  postgres-payment:
    image: postgres:latest
    environment:
      POSTGRES_DB: payment
      POSTGRES_USER: bestuser
      POSTGRES_PASSWORD: secretPassword
    ports:
      - "5435:5432"
    restart: unless-stopped
    networks:
      - parser-net

  mongo:
    image: mongo
    restart: on-failure
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    networks:
      - parser-net

  mongo-customer:
    image: mongo
    restart: on-failure
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_customer_data:/data/db
    networks:
      - parser-net

  kafka-1:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=PVjHlx7ESeesq55jeB6Efw
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9090,EXTERNAL://${HOSTNAME:-localhost}:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    networks:
      - parser-net

  kafka-2:
    image: bitnami/kafka:latest
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_KRAFT_CLUSTER_ID=PVjHlx7ESeesq55jeB6Efw
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9090,EXTERNAL://${HOSTNAME:-localhost}:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    networks:
      - parser-net


  kafka-3:
    image: bitnami/kafka:latest
    ports:
      - "9096:9096"
    environment:
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_KRAFT_CLUSTER_ID=PVjHlx7ESeesq55jeB6Efw
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-3:9090,EXTERNAL://${HOSTNAME:-localhost}:9096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    networks:
      - parser-net

volumes:
  mongo_data:
  mongo_customer_data:

networks:
  parser-net:
    driver: bridge
