version: '3'

services:

  mysql-parse:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: parser
      MYSQL_USER: bestuser
      MYSQL_PASSWORD: secretPassword
    ports:
      - "3307:3306"
    restart: unless-stopped
    networks:
      - parser-net

  postgres-stock:
    image: postgres:latest
    environment:
      POSTGRES_DB: stock
      POSTGRES_USER: bestuser
      POSTGRES_PASSWORD: secretPassword
    ports:
      - "5431:5432"
    restart: unless-stopped
    networks:
      - parser-net

  postgres-product:
    image: postgres:latest
    environment:
      POSTGRES_DB: product
      POSTGRES_USER: bestuser
      POSTGRES_PASSWORD: secretPassword
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - parser-net

  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    networks:
      - parser-net

  mongo-customer:
    image: mongo
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_customer_data:/data/db
    networks:
      - parser-net

volumes:
  mongo_data:
  mongo_customer_data:

networks:
  parser-net:
    driver: bridge
